-- Ajout de 100 ingrédients fictifs
INSERT INTO ingredient (title, calorie, id_ingredient_category) VALUES
                                                                    ('Carotte', '41 kcal', 1),
                                                                    ('Brocoli', '34 kcal', 1),
                                                                    ('Épinard', '23 kcal', 1),
                                                                    ('Poivron Rouge', '31 kcal', 1),
                                                                    ('Radis', '16 kcal', 1),
                                                                    ('Courgette', '17 kcal', 1),
                                                                    ('Aubergine', '25 kcal', 1),
                                                                    ('Céleri', '16 kcal', 1),
                                                                    ('Chou-fleur', '25 kcal', 1),
                                                                    ('Navet', '28 kcal', 1),
                                                                    ('Basilic', '23 kcal', 1),
                                                                    ('Menthe', '44 kcal', 1),
                                                                    ('Cerise', '63 kcal', 2),
                                                                    ('Banane', '89 kcal', 2),
                                                                    ('Fraise', '32 kcal', 2),
                                                                    ('Mangue', '60 kcal', 2),
                                                                    ('Papaye', '43 kcal', 2),
                                                                    ('Ananas', '50 kcal', 2),
                                                                    ('Raisin', '69 kcal', 2),
                                                                    ('Pêche', '39 kcal', 2),
                                                                    ('Abricot', '48 kcal', 2),
                                                                    ('Prune', '46 kcal', 2),
                                                                    ('Kiwi', '61 kcal', 2),
                                                                    ('Orange', '47 kcal', 2),
                                                                    ('Clémentine', '47 kcal', 2),
                                                                    ('Framboise', '52 kcal', 2),
                                                                    ('Mûre', '43 kcal', 2),
                                                                    ('Groseille', '56 kcal', 2),
                                                                    ('Noix de coco', '354 kcal', 2),
                                                                    ('Poulet grillé', '165 kcal', 3),
                                                                    ('Dinde', '104 kcal', 3),
                                                                    ('Boeuf haché', '250 kcal', 3),
                                                                    ('Porc', '242 kcal', 3),
                                                                    ('Bacon', '541 kcal', 3),
                                                                    ('Jambon', '145 kcal', 3),
                                                                    ('Agneau', '294 kcal', 3),
                                                                    ('Canard', '337 kcal', 3),
                                                                    ('Lapin', '173 kcal', 3),
                                                                    ('Saucisse', '346 kcal', 3),
                                                                    ('Steak de boeuf', '271 kcal', 3),
                                                                    ('Escalope de veau', '182 kcal', 3),
                                                                    ('Mouton', '294 kcal', 3),
                                                                    ('Fromage de chèvre', '364 kcal', 4),
                                                                    ('Camembert', '299 kcal', 4),
                                                                    ('Gruyère', '413 kcal', 4),
                                                                    ('Parmesan', '431 kcal', 4),
                                                                    ('Mozzarella', '280 kcal', 4),
                                                                    ('Cantal', '394 kcal', 4),
                                                                    ('Brie', '334 kcal', 4),
                                                                    ('Roquefort', '369 kcal', 4),
                                                                    ('Yaourt', '59 kcal', 4),
                                                                    ('Crème fraîche', '193 kcal', 4),
                                                                    ('Beurre', '717 kcal', 4),
                                                                    ('Mascarpone', '455 kcal', 4),
                                                                    ('Ricotta', '174 kcal', 4),
                                                                    ('Bleu', '353 kcal', 4),
                                                                    ('Comté', '380 kcal', 4),
                                                                    ('Mimolette', '351 kcal', 4),
                                                                    ('Échalote', '72 kcal', 1),
                                                                    ('Poireau', '61 kcal', 1),
                                                                    ('Champignon', '22 kcal', 1),
                                                                    ('Oignon', '40 kcal', 1),
                                                                    ('Ail', '149 kcal', 1),
                                                                    ('Laitue', '15 kcal', 1),
                                                                    ('Roquette', '25 kcal', 1),
                                                                    ('Petits pois', '81 kcal', 1),
                                                                    ('Haricot vert', '31 kcal', 1),
                                                                    ('Pomme de terre', '77 kcal', 1),
                                                                    ('Chou', '25 kcal', 1),
                                                                    ('Bette', '19 kcal', 1),
                                                                    ('Mâche', '20 kcal', 1),
                                                                    ('Cassis', '63 kcal', 2),
                                                                    ('Melon', '33 kcal', 2),
                                                                    ('Pastèque', '30 kcal', 2),
                                                                    ('Pomelo', '42 kcal', 2),
                                                                    ('Litchi', '66 kcal', 2),
                                                                    ('Pamplemousse', '50 kcal', 2),
                                                                    ('Mirabelle', '62 kcal', 2),
                                                                    ('Boeuf séché', '410 kcal', 3),
                                                                    ('Foie gras', '462 kcal', 3),
                                                                    ('Côtelette de porc', '236 kcal', 3),
                                                                    ('Pigeon', '142 kcal', 3),
                                                                    ('Filet mignon', '224 kcal', 3),
                                                                    ('Pintade', '110 kcal', 3),
                                                                    ('Quail', '119 kcal', 3),
                                                                    ('Viande hachée de veau', '212 kcal', 3),
                                                                    ('Saumon fumé', '117 kcal', 3),
                                                                    ('Lait écrémé', '34 kcal', 4),
                                                                    ('Lait entier', '64 kcal', 4),
                                                                    ('Crème légère', '292 kcal', 4),
                                                                    ('Petit suisse', '60 kcal', 4),
                                                                    ('Kefir', '45 kcal', 4),
                                                                    ('Fromage blanc', '72 kcal', 4),
                                                                    ('Chocolat au lait', '546 kcal', 4),
                                                                    ('Chocolat noir', '598 kcal', 4),
                                                                    ('Fromage fondu', '215 kcal', 4),
                                                                    ('Sérac', '143 kcal', 4),
                                                                    ('Emmental', '384 kcal', 4),
                                                                    ('Chèvre frais', '320 kcal', 4),
                                                                    ('Reblochon', '310 kcal', 4);

-- Ajout de 100 nouveaux ingrédients fictifs
INSERT INTO ingredient (title, calorie, id_ingredient_category) VALUES
                                                                    ('Artichaut', '47 kcal', 1),
                                                                    ('Asperge', '20 kcal', 1),
                                                                    ('Betterave', '43 kcal', 1),
                                                                    ('Fenouil', '31 kcal', 1),
                                                                    ('Radicchio', '23 kcal', 1),
                                                                    ('Topinambour', '76 kcal', 1),
                                                                    ('Endive', '17 kcal', 1),
                                                                    ('Poivron Jaune', '27 kcal', 1),
                                                                    ('Chou de Bruxelles', '43 kcal', 1),
                                                                    ('Chou frisé', '33 kcal', 1),
                                                                    ('Cresson', '11 kcal', 1),
                                                                    ('Fenugrec', '323 kcal', 1),
                                                                    ('Chicorée', '23 kcal', 1),
                                                                    ('Moutarde verte', '27 kcal', 1),
                                                                    ('Courge Butternut', '45 kcal', 1),
                                                                    ('Patate douce', '86 kcal', 1),
                                                                    ('Pois chiche', '164 kcal', 1),
                                                                    ('Haricot noir', '341 kcal', 1),
                                                                    ('Lentille', '116 kcal', 1),
                                                                    ('Fève', '88 kcal', 1),
                                                                    ('Pois mange-tout', '42 kcal', 1),
                                                                    ('Brocoli romanesco', '25 kcal', 1),
                                                                    ('Navet boule d’or', '28 kcal', 1),
                                                                    ('Oignon vert', '32 kcal', 1),
                                                                    ('Citron', '29 kcal', 2),
                                                                    ('Framboise sauvage', '52 kcal', 2),
                                                                    ('Goyave', '68 kcal', 2),
                                                                    ('Figue', '74 kcal', 2),
                                                                    ('Datte', '277 kcal', 2),
                                                                    ('Grenade', '83 kcal', 2),
                                                                    ('Papaye solo', '39 kcal', 2),
                                                                    ('Fruit du dragon', '50 kcal', 2),
                                                                    ('Kaki', '81 kcal', 2),
                                                                    ('Mangoustan', '73 kcal', 2),
                                                                    ('Nèfle', '47 kcal', 2),
                                                                    ('Ramboutan', '82 kcal', 2),
                                                                    ('Tamarillo', '31 kcal', 2),
                                                                    ('Quetsche', '50 kcal', 2),
                                                                    ('Nectarine', '44 kcal', 2),
                                                                    ('Citron vert', '30 kcal', 2),
                                                                    ('Physalis', '53 kcal', 2),
                                                                    ('Carambole', '31 kcal', 2),
                                                                    ('Litchi séché', '300 kcal', 2),
                                                                    ('Châtaigne', '245 kcal', 2),
                                                                    ('Pignon de pin', '673 kcal', 2),
                                                                    ('Caille', '162 kcal', 3),
                                                                    ('Escalope de poulet', '165 kcal', 3),
                                                                    ('Pied de porc', '240 kcal', 3),
                                                                    ('Tendron de veau', '174 kcal', 3),
                                                                    ('Blanc de dinde', '135 kcal', 3),
                                                                    ('Joues de porc', '206 kcal', 3),
                                                                    ('Filet de lapin', '173 kcal', 3),
                                                                    ('Rognons', '115 kcal', 3),
                                                                    ('Andouille', '305 kcal', 3),
                                                                    ('Terrine de canard', '249 kcal', 3),
                                                                    ('Rillette de porc', '565 kcal', 3),
                                                                    ('Brochette de boeuf', '251 kcal', 3),
                                                                    ('Viande des Grisons', '168 kcal', 3),
                                                                    ('Foie de veau', '135 kcal', 3),
                                                                    ('Foie de volaille', '167 kcal', 3),
                                                                    ('Steak haché', '233 kcal', 3),
                                                                    ('Aile de poulet', '203 kcal', 3),
                                                                    ('Pâté de campagne', '339 kcal', 3),
                                                                    ('Longe de porc', '214 kcal', 3),
                                                                    ('Tartare de boeuf', '222 kcal', 3),
                                                                    ('Fromage de brebis', '360 kcal', 4),
                                                                    ('Petit brie', '334 kcal', 4),
                                                                    ('Maroilles', '340 kcal', 4),
                                                                    ('Brousse', '109 kcal', 4),
                                                                    ('Fromage frais', '145 kcal', 4),
                                                                    ('Chèvre sec', '451 kcal', 4),
                                                                    ('Tome de Savoie', '334 kcal', 4),
                                                                    ('Crottin de Chavignol', '320 kcal', 4),
                                                                    ('Reblochon de Savoie', '318 kcal', 4),
                                                                    ('Fromage blanc à 0%', '45 kcal', 4),
                                                                    ('Burrata', '285 kcal', 4),
                                                                    ('Crème Chantilly', '335 kcal', 4),
                                                                    ('Crème double', '459 kcal', 4),
                                                                    ('Mozzarella di Bufala', '270 kcal', 4),
                                                                    ('Saint-Nectaire', '336 kcal', 4),
                                                                    ('Brillat-Savarin', '365 kcal', 4),
                                                                    ('Edam', '357 kcal', 4),
                                                                    ('Cancoillotte', '120 kcal', 4),
                                                                    ('Morbier', '329 kcal', 4),
                                                                    ('Port-Salut', '310 kcal', 4),
                                                                    ('Pavé d’Affinois', '351 kcal', 4),
                                                                    ('Gouda', '356 kcal', 4),
                                                                    ('Livarot', '260 kcal', 4),
                                                                    ('Bleu d’Auvergne', '353 kcal', 4),
                                                                    ('Coulommiers', '333 kcal', 4),
                                                                    ('Camembert au lait cru', '299 kcal', 4),
                                                                    ('Saint-Marcellin', '291 kcal', 4),
                                                                    ('Pont-l’Évêque', '320 kcal', 4),
                                                                    ('Tomme des Pyrénées', '337 kcal', 4),
                                                                    ('Mimolette vieille', '386 kcal', 4),
                                                                    ('Crottin de Chèvre', '320 kcal', 4),
                                                                    ('Mont d’Or', '317 kcal', 4),
                                                                    ('Chocolat blanc', '539 kcal', 4),
                                                                    ('Fromage à raclette', '361 kcal', 4),
                                                                    ('Chocolat aux noisettes', '573 kcal', 4),
                                                                    ('Crème dessert', '145 kcal', 4),
                                                                    ('Crème brûlée', '291 kcal', 4);


-- Ajout de la catégorie "Arachides et Noix"
INSERT INTO ingredient_category (id_ingredient_category, title) VALUES (5,'Arachides et Noix');

-- Récupération de l'ID de la nouvelle catégorie pour l'insertion des ingrédients
-- (Supposons qu'il s'agisse de l'ID 5 si la table est remplie en ordre croissant)
-- Vous pouvez vérifier l'ID réel avec une requête SELECT avant d'insérer les données si besoin.

-- Insertion d'ingrédients dans la catégorie "Arachides et Noix"
INSERT INTO ingredient (title, calorie, id_ingredient_category) VALUES
                                                                    ('Amande', '579 kcal', 5),
                                                                    ('Noisette', '628 kcal', 5),
                                                                    ('Noix de cajou', '553 kcal', 5),
                                                                    ('Pistache', '562 kcal', 5),
                                                                    ('Noix de pécan', '691 kcal', 5),
                                                                    ('Noix de macadamia', '718 kcal', 5),
                                                                    ('Noix du Brésil', '656 kcal', 5),
                                                                    ('Arachide', '567 kcal', 5),
                                                                    ('Noix', '654 kcal', 5),
                                                                    ('Noix de Grenoble', '654 kcal', 5),
                                                                    ('Noix de pin', '673 kcal', 5),
                                                                    ('Noix de bancoul', '705 kcal', 5),
                                                                    ('Graines de tournesol', '584 kcal', 5),
                                                                    ('Graines de sésame', '573 kcal', 5),
                                                                    ('Graines de lin', '534 kcal', 5),
                                                                    ('Graines de chia', '486 kcal', 5),
                                                                    ('Noix de kola', '150 kcal', 5),
                                                                    ('Beurre de cacahuète', '589 kcal', 5),
                                                                    ('Graines de citrouille', '559 kcal', 5),
                                                                    ('Noix de muscade', '525 kcal', 5),
                                                                    ('Graines de courge', '574 kcal', 5),
                                                                    ('Amande grillée', '590 kcal', 5),
                                                                    ('Noisette grillée', '628 kcal', 5),
                                                                    ('Arachide grillée', '599 kcal', 5),
                                                                    ('Pistache grillée', '562 kcal', 5),
                                                                    ('Cajou grillée', '553 kcal', 5),
                                                                    ('Noix de pécan grillée', '691 kcal', 5),
                                                                    ('Noix de macadamia grillée', '718 kcal', 5),
                                                                    ('Noix du Brésil grillée', '656 kcal', 5),
                                                                    ('Praliné aux noisettes', '635 kcal', 5),
                                                                    ('Pâte de sésame', '595 kcal', 5),
                                                                    ('Graines de chanvre', '553 kcal', 5),
                                                                    ('Graines de pavot', '525 kcal', 5),
                                                                    ('Beurre d’amande', '614 kcal', 5),
                                                                    ('Graines de nigelle', '380 kcal', 5),
                                                                    ('Purée de noisettes', '650 kcal', 5),
                                                                    ('Praliné d’amandes', '600 kcal', 5),
                                                                    ('Graines de courge grillées', '559 kcal', 5),
                                                                    ('Graines de tournesol grillées', '584 kcal', 5),
                                                                    ('Amande effilée', '575 kcal', 5),
                                                                    ('Noix de macadamia crue', '718 kcal', 5),
                                                                    ('Graines de pavot bleu', '525 kcal', 5),
                                                                    ('Amande émondée', '570 kcal', 5),
                                                                    ('Farine de noix de coco', '416 kcal', 5),
                                                                    ('Farine d’amande', '610 kcal', 5),
                                                                    ('Noix caramélisée', '678 kcal', 5),
                                                                    ('Cacahuète enrobée', '500 kcal', 5),
                                                                    ('Noix de cajou au miel', '585 kcal', 5);

-- Fin de l'insertion des ingrédients pour la catégorie "Arachides et Noix"

